/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.41
 * Generated at: 2025-07-05 12:54:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/D:/Web%20Development%207/Freelancer%20Portal/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Freelancer_MarketPlcae/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar!/META-INF/c.tld", Long.valueOf(1602854172000L));
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar", Long.valueOf(1748715636586L));
    _jspx_dependants.put("/Components/allCss.jsp", Long.valueOf(1750773422740L));
    _jspx_dependants.put("/Components/Navbar.jsp", Long.valueOf(1750773444667L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\">\r\n");
      out.write("  <title>Freelancer Marketplace Portal</title>\r\n");
      out.write("  ");
      out.write("<!-- â Bootstrap CSS -->\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- â Font Awesome Icons -->\r\n");
      out.write("<link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- â Bootstrap Bundle JS (with Popper for dropdowns) -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <style>\r\n");
      out.write("    .hero {\r\n");
      out.write("  background: url('https://images.unsplash.com/photo-1556740749-887f6717d7e4?auto=format&fit=crop&w=1600') center/cover no-repeat;\r\n");
      out.write("  position: relative;\r\n");
      out.write("  height: 100vh;\r\n");
      out.write("  display: flex;\r\n");
      out.write("  align-items: center;\r\n");
      out.write("  justify-content: center;\r\n");
      out.write("  overflow: hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".hero .overlay {\r\n");
      out.write("  z-index: 1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".hero .container {\r\n");
      out.write("  z-index: 2;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".hero h1, .hero p {\r\n");
      out.write("  color: #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".hero .btn {\r\n");
      out.write("  padding: 0.75rem 1.5rem;\r\n");
      out.write("  font-size: 1.1rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    .features .card {\r\n");
      out.write("      border: none;\r\n");
      out.write("      transition: transform .3s;\r\n");
      out.write("    }\r\n");
      out.write("    .features .card:hover {\r\n");
      out.write("      transform: translateY(-8px);\r\n");
      out.write("      box-shadow: 0 8px 30px rgba(0,0,0,0.1);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .steps .step {\r\n");
      out.write("      text-align: center;\r\n");
      out.write("      padding: 1rem;\r\n");
      out.write("    }\r\n");
      out.write("    .steps .step i {\r\n");
      out.write("      font-size: 3rem;\r\n");
      out.write("      color: #0d6efd;\r\n");
      out.write("      margin-bottom: .5rem;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .footer {\r\n");
      out.write("      background: #f8f9fa;\r\n");
      out.write("      padding: 2rem 0;\r\n");
      out.write("      margin-top: 2rem;\r\n");
      out.write("      text-align: center;\r\n");
      out.write("    }\r\n");
      out.write("  </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("	.custom-dark-nav {\r\n");
      out.write("		background-color: #1f1f2e; /* modern dark tone */\r\n");
      out.write("		box-shadow: 0 2px 6px rgba(0, 0, 0, 0.5);\r\n");
      out.write("	}\r\n");
      out.write("	.custom-dark-nav .nav-link,\r\n");
      out.write("	.custom-dark-nav .navbar-brand {\r\n");
      out.write("		color: #f1f1f1 !important;\r\n");
      out.write("	}\r\n");
      out.write("	.custom-dark-nav .nav-link:hover {\r\n");
      out.write("		color: #00c6ff !important; /* modern cyan-blue hover */\r\n");
      out.write("	}\r\n");
      out.write("	.dropdown-menu {\r\n");
      out.write("		background-color: #2c2c3c;\r\n");
      out.write("	}\r\n");
      out.write("	.dropdown-menu .dropdown-item {\r\n");
      out.write("		color: #f1f1f1;\r\n");
      out.write("	}\r\n");
      out.write("	.dropdown-menu .dropdown-item:hover {\r\n");
      out.write("		background-color: #3a3a50;\r\n");
      out.write("		color: #00c6ff;\r\n");
      out.write("	}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg custom-dark-nav\">\r\n");
      out.write("	<div class=\"container-fluid\">\r\n");
      out.write("		<a class=\"navbar-brand fw-bold\" href=\"index.jsp\">\r\n");
      out.write("			<i class=\"fa-solid fa-briefcase\"></i> FreeLancePro\r\n");
      out.write("		</a>\r\n");
      out.write("\r\n");
      out.write("		<button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\"\r\n");
      out.write("			data-bs-target=\"#navbarNav\" aria-controls=\"navbarNav\"\r\n");
      out.write("			aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("			<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("		</button>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"collapse navbar-collapse\" id=\"navbarNav\">\r\n");
      out.write("			<ul class=\"navbar-nav ms-auto mb-2 mb-lg-0\">\r\n");
      out.write("\r\n");
      out.write("				<!-- Not Logged In -->\r\n");
      out.write("				");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Hero Section -->\r\n");
      out.write("<section class=\"hero position-relative\">\r\n");
      out.write("  <div class=\"overlay position-absolute top-0 start-0 w-100 h-100 bg-dark opacity-75\"></div>\r\n");
      out.write("  <div class=\"container position-relative text-white text-center py-5\">\r\n");
      out.write("    <h1 class=\"display-4 fw-bold mb-3\">Find the Perfect Match for Your Projects</h1>\r\n");
      out.write("    <p class=\"lead mb-4\">Hire expert freelancers, grow your skills, and manage your workflow efficiently.</p>\r\n");
      out.write("    <a href=\"freelancer/register.jsp\" class=\"btn btn-lg btn-primary me-3\">Join Now</a>\r\n");
      out.write("    <a href=\"#how-it-works\" class=\"btn btn-lg btn-outline-light\">Learn More</a>\r\n");
      out.write("  </div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Features -->\r\n");
      out.write("<section class=\"features py-5\">\r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("    <div class=\"row g-4\">\r\n");
      out.write("      <div class=\"col-md-4\">\r\n");
      out.write("        <div class=\"card text-center p-4\">\r\n");
      out.write("          <i class=\"fas fa-user-tie fa-3x text-primary mb-3\"></i>\r\n");
      out.write("          <h5>For Clients</h5>\r\n");
      out.write("          <p>Post projects, review bids, and hire skilled freelancers with confidence.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-md-4\">\r\n");
      out.write("        <div class=\"card text-center p-4\">\r\n");
      out.write("          <i class=\"fas fa-laptop-code fa-3x text-primary mb-3\"></i>\r\n");
      out.write("          <h5>For Freelancers</h5>\r\n");
      out.write("          <p>Explore opportunities, bid on projects, and grow your portfolio with ease.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-md-4\">\r\n");
      out.write("        <div class=\"card text-center p-4\">\r\n");
      out.write("          <i class=\"fas fa-users-cog fa-3x text-primary mb-3\"></i>\r\n");
      out.write("          <h5>For Admins</h5>\r\n");
      out.write("          <p>Manage users, track transactions, and maintain platform integrity effortlessly.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<!-- How It Works -->\r\n");
      out.write("<section id=\"how-it-works\" class=\"py-5 bg-light\">\r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("    <h2 class=\"text-center mb-4\">How It Works</h2>\r\n");
      out.write("    <div class=\"row steps g-4\">\r\n");
      out.write("      <div class=\"col-md-3 step\">\r\n");
      out.write("        <i class=\"fas fa-pencil-alt\"></i>\r\n");
      out.write("        <h6>Post Project</h6>\r\n");
      out.write("        <p>Describe your needs and set a budget.</p>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-md-3 step\">\r\n");
      out.write("        <i class=\"fas fa-gavel\"></i>\r\n");
      out.write("        <h6>Review Bids</h6>\r\n");
      out.write("        <p>Get bids from talented freelancers and choose the best fit.</p>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-md-3 step\">\r\n");
      out.write("        <i class=\"fas fa-cogs\"></i>\r\n");
      out.write("        <h6>Start Work</h6>\r\n");
      out.write("        <p>Collaborate, track progress, and communicate easily.</p>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-md-3 step\">\r\n");
      out.write("        <i class=\"fas fa-hand-holding-usd\"></i>\r\n");
      out.write("        <h6>Pay & Review</h6>\r\n");
      out.write("        <p>Securely release payment and rate your experience.</p>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<!-- Testimonials -->\r\n");
      out.write("<section class=\"py-5 bg-light text-center\">\r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("    <h2 class=\"mb-5\">What Our Users Say</h2>\r\n");
      out.write("    <div class=\"row g-4 justify-content-center\">\r\n");
      out.write("\r\n");
      out.write("      <!-- Client Testimonial -->\r\n");
      out.write("      <div class=\"col-md-4\">\r\n");
      out.write("        <div class=\"card border-0 shadow-sm p-4 h-100\">\r\n");
      out.write("          <img src=\"https://randomuser.me/api/portraits/women/44.jpg\" class=\"rounded-circle mx-auto mb-3\" alt=\"Client Image\" width=\"80\" height=\"80\">\r\n");
      out.write("          <h5 class=\"fw-bold\">Ayesha Kapoor</h5>\r\n");
      out.write("          <small class=\"text-muted\">Startup Founder</small>\r\n");
      out.write("          <p class=\"mt-3\">“I posted a project and hired a developer within 48 hours. Seamless experience and top-quality work!”</p>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- Freelancer Testimonial -->\r\n");
      out.write("      <div class=\"col-md-4\">\r\n");
      out.write("        <div class=\"card border-0 shadow-sm p-4 h-100\">\r\n");
      out.write("          <img src=\"https://randomuser.me/api/portraits/men/32.jpg\" class=\"rounded-circle mx-auto mb-3\" alt=\"Freelancer Image\" width=\"80\" height=\"80\">\r\n");
      out.write("          <h5 class=\"fw-bold\">Rahul Sharma</h5>\r\n");
      out.write("          <small class=\"text-muted\">Full-Stack Developer</small>\r\n");
      out.write("          <p class=\"mt-3\">“WorkLink helped me land consistent freelance projects and build my portfolio quickly.”</p>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- Admin Testimonial -->\r\n");
      out.write("      <div class=\"col-md-4\">\r\n");
      out.write("        <div class=\"card border-0 shadow-sm p-4 h-100\">\r\n");
      out.write("          <img src=\"https://randomuser.me/api/portraits/men/85.jpg\" class=\"rounded-circle mx-auto mb-3\" alt=\"Admin Image\" width=\"80\" height=\"80\">\r\n");
      out.write("          <h5 class=\"fw-bold\">Kunal Verma</h5>\r\n");
      out.write("          <small class=\"text-muted\">Platform Admin</small>\r\n");
      out.write("          <p class=\"mt-3\">“Managing users, payments, and projects is extremely easy through the admin dashboard.”</p>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Footer -->\r\n");
      out.write("<footer class=\"footer\">\r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("    <p>&copy; 2025 Freelancer Marketplace Portal (WorkLink). All Rights Reserved.</p>\r\n");
      out.write("    <small>Designed for freelancers, clients, and admins to collaborate and grow together.</small>\r\n");
      out.write("  </div>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /Components/Navbar.jsp(44,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty userObj}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("					<li class=\"nav-item\">\r\n");
        out.write("						<a class=\"nav-link\" href=\"freelancer/register.jsp\">\r\n");
        out.write("							<i class=\"fa-solid fa-user-plus\"></i> Become a Freelancer\r\n");
        out.write("						</a>\r\n");
        out.write("					</li>\r\n");
        out.write("					<li class=\"nav-item\">\r\n");
        out.write("						<a class=\"nav-link\" href=\"client/register.jsp\">\r\n");
        out.write("							<i class=\"fa-solid fa-user-plus\"></i> Hire Talent\r\n");
        out.write("						</a>\r\n");
        out.write("					</li>\r\n");
        out.write("					<li class=\"nav-item dropdown\">\r\n");
        out.write("						<a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"loginDropdown\" role=\"button\"\r\n");
        out.write("							data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
        out.write("							<i class=\"fa-solid fa-right-to-bracket\"></i> Login\r\n");
        out.write("						</a>\r\n");
        out.write("						<ul class=\"dropdown-menu dropdown-menu-end\" aria-labelledby=\"loginDropdown\">\r\n");
        out.write("							<li><a class=\"dropdown-item\" href=\"client/login.jsp\">Client Login</a></li>\r\n");
        out.write("							<li><a class=\"dropdown-item\" href=\"freelancer/login.jsp\">Freelancer Login</a></li>\r\n");
        out.write("							<li><a class=\"dropdown-item\" href=\"admin/login.jsp\">Admin Login</a></li>\r\n");
        out.write("						</ul>\r\n");
        out.write("					</li>\r\n");
        out.write("				");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }
}
